### ISSUE TITLE
[Feature Request] Allow users to supply file name of exported .a11ytest file

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/axe-windows#104]
**Is your feature request related to a problem? Please describe.**

In UI tests that generate multiple a11ytest files, it is desirable to distinguish them in the resulting output. The current `Config.Builder` allows the user to specify a directory, but the name of the resulting .a11ytest file is determined by Axe.Windows. It would be helpful if the user could supply a file name provider to the `Builder` or a file name to `Scan()`. Currently the user needs to rename the resulting files, as we do here:

https://github.com/microsoft/accessibility-insights-windows/blob/9ea46a709b30d8d7684998fe8bba9951d38bd180/src/UITests/UILibrary/AIWinDriver.cs#L54

**Describe the solution you'd like**
Alongside the existing output directory method [here](https://github.com/microsoft/axe-windows/blob/master/docs/AutomationReference.md#withoutputdirectory), the config could provide a `WithOutputFileName((Func<string> nameProvider)` method as well.

**Describe alternatives you've considered**
The user can rename the returned file themselves. If the library can do this for them, it would be a bit easier.

**Comment by Sirisha-Kommushetty** [comment]
@RobGallo - Did you connect with Karan on this?

**Comment by Sirisha-Kommushetty** [comment]
We're not doing this at this time.

**Comment by jalkire** [comment]
@Sirisha-Kommushetty Why not?
