### ISSUE TITLE
[BUG] False positive for BoundingRectangleNotNull for group elements in Edge

### ISSUE THREAD

**Issue by RobGallo** [microsoft/axe-windows#142]
An app creator contacted us with an AI-Web scan of an application which included web-based content displayed in Edge (original, not based on Chromium). Seemingly normal div tags are converted by Edge into UIA elements with the control type of group. But these elements have bounding rectangles which are null.
Since this is not resolvable by the end user, and not likely to be resolved in the older version of Edge, we should not show this error in the case where the bounding rectangle is null for a group inside Edge.

**Comment by Sirisha-Kommushetty** [comment]
Seems straightforward to me.

**Comment by RobGallo** [comment]
Fixed in PR #144
