### ISSUE TITLE
Evaluate applicability of ControlShouldSupportTextPattern to WinForm NumericUpDown controls

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/axe-windows#150]
The NumericUpDown control in WinForm does not support TextPattern ([tracking issue](https://github.com/dotnet/winforms/issues/1588)). It consists of a spinner up/down control alongside an edit control showing the selected number. 

This issue is to track whether this is a false positive on our end - e.g. should the NumericUpDown control be excluded from the ControlShouldSupportTextPattern check? ~Typing is not allowed in the control - the only way to edit the numbers is through the up/down arrow keys.~ (It's allowed for numbers, I had tried letters earlier). The value change is announced in NVDA, for example.

Example application: 
[WindowsFormsApp2.zip](https://github.com/microsoft/axe-windows/files/3632621/WindowsFormsApp2.zip)

**Comment by ferBonnin** [comment]
@karanbirsingh 3 things:

- the example app seems to allow writing a number in the NumericUpDown control
- how will a user of Speech to text would introduce a number? 
- Is it expected to use the up arrow 100 times if you want to write a 100?

**Comment by karanbirsingh** [comment]
@ferBonnin thanks, I must have tried letters earlier instead of numbers. I'll chat with Rob to get his take as well

**Comment by ferBonnin** [comment]
@karanbirsingh is this active?

**Comment by karanbirsingh** [comment]
@ferBonnin yes, I am looking into it with @RobGallo

**Comment by karanbirsingh** [comment]
We looked at this in more detail and verified all edit controls should support the text pattern per the UIA documentation here: https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-supporteditcontroltype#required-control-patterns
