### ISSUE TITLE
[ENG] SystemAbstractionsTests are not running in build loop

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/axe-windows#152]
Please check whether the bug has [already been filed](https://github.com/Microsoft/axe-windows/issues).

**Describe the bug**
Tests from SystemAbstractionsTests.dll are not running in the build loop. 

**To Reproduce**
1. Open the results of a build loop (I tried both PR builds and official builds)
2. Open the test results
3. Search for any of the following unit tests
    - RegistryGetValue_Matches
    - CreateDirectory_CreatesDirectory
    - CurrentDirectory_Matches
    - DateTime_Matches
    - DirectoryExists_ReturnsExpected

**Expected behavior**
Unit tests should be executing

**Actual behavior**
Unit tests do not execute. There is, however, the following message in the logs:
[MSTest][Discovery][d:\a\1\s\src\SystemAbstractionsTests\bin\Release\netcoreapp2.1\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll] Unable to load types from the test source 'd:\a\1\s\src\SystemAbstractionsTests\bin\Release\netcoreapp2.1\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll'. Some or all of the tests in this source may not be discovered.
[MSTest][Discovery][d:\a\1\s\src\SystemAbstractionsTests\bin\Release\netcoreapp2.1\SystemAbstractionsTests.dll] Unable to load types from the test source 'd:\a\1\s\src\SystemAbstractionsTests\bin\Release\netcoreapp2.1\SystemAbstractionsTests.dll'. Some or all of the tests in this source may not be discovered.
[MSTest][Discovery][d:\a\1\s\src\packages\MSTest.TestAdapter.1.4.0\build\netcoreapp1.0\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll] Unable to load types from the test source 'd:\a\1\s\src\packages\MSTest.TestAdapter.1.4.0\build\netcoreapp1.0\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll'. Some or all of the tests in this source may not be discovered.
[MSTest][Discovery][d:\a\1\s\src\packages\MSTest.TestAdapter.1.4.0\build\uap10.0\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll] Unable to load types from the test source 'd:\a\1\s\src\packages\MSTest.TestAdapter.1.4.0\build\uap10.0\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll'. Some or all of the tests in this source may not be discovered.

**Additional context**
These unit tests work as expected (meaning they are discovered and run successfully) when run locally

**Comment by devaradhanm** [comment]
I will investigate & get back to you.

**Comment by devaradhanm** [comment]
I didn't spend time investigating. I am able to get the mentioned tests run locally but these are not being run in CI. I have moved this to ready for work.

**Comment by DaveTryon** [comment]
I believe @RobGallo is looking at this. I'll leave it to him to self-assign if he wishes

**Comment by DaveTryon** [comment]
Assigned this to myself at Rob's request (and since I'm DRI this week)

**Comment by DaveTryon** [comment]
This is still on Rob's plate. I picked up the wrong issue
