### ISSUE TITLE
[Feature Request] Add rule to ensure the descendants of off screen elements are also off screen.

### ISSUE THREAD

**Issue by RobGallo** [microsoft/axe-windows#161]
### new rule

Based on https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.automationelement.automationelementinformation.isoffscreen?view=netframework-4.8:

“When the value is true for a container, it is also true for the container element's descendants.”

We should add a rule which validates this policy.

**Comment by ferBonnin** [comment]
Reviewed this with PMs and Leads, this looks like a good suggestion, but we need to schedule time to do this feature @RobGallo  is this a 2-day thing or a 2-week thing?

**Comment by RobGallo** [comment]
@ferBonnin, It's more of a two day thing.

**Comment by RobGallo** [comment]
Fixed in 0.9.1.
