### ISSUE TITLE
[Feature Request] Add rules to ensure that an element's clickable point and IsOffscreen property agree.

### ISSUE THREAD

**Issue by RobGallo** [microsoft/axe-windows#162]
### new rule

Based on https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.automationelement.automationelementinformation.isoffscreen?view=netframework-4.8:

“If the element has a clickable point that can cause it to be focused, it is considered to be onscreen even when a portion of the element is off screen.”

Based on this, there should be two rules:
1. When an element's clickable point is on screen, its IsOffscreen property should be set to false.
2. When an element's clickable point is off screen, its IsOffscreen property should be set to true.

**Comment by ferBonnin** [comment]
Reviewed this with PMs and Leads, this looks like a good suggestion, but we need to schedule time to do this feature. @RobGallo is this a 2-day thing or a 2-week thing?

**Comment by RobGallo** [comment]
@ferBonnin, it's more of a two day thing.

**Comment by ferBonnin** [comment]
@peterdur do we want to take this and the other rule (Also 2 days) as a feature or in slack time?

**Comment by RobGallo** [comment]
This issue was fixed and released in axe-windows version 0.9.0.
