### ISSUE TITLE
[General Question] Are UWP apps supported?

### ISSUE THREAD

**Issue by benabbon** [microsoft/axe-windows#251]
## Are UWP apps supported?

I'd love to test my UWP app, where I have Selenium UITests running on the build pipeline.
When I try to integrate the package, I get this error:
NU1202: Package Axe.Windows 0.3.5-prerelease is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763). Package Axe.Windows 0.3.5-prerelease supports: net471 (.NETFramework,Version=v4.7.1)

**Comment by RobGallo** [comment]
@benabbon 

Is there a way we could reproduce the error locally?

**Comment by benabbon** [comment]
@RobGallo A fresh UWP app, with a fresh UWP unit test project targeting windows 10.0.17763 created by VS 2019, and then add the axe-windows as nuget to the UWP unit test project.

I'll try to create a repo with this structure today and share it with you.

**Comment by benabbon** [comment]
@RobGallo No need for a UWP project. Just create an empty UWP Unit test project from Visual studio 2019, and try to add the Axe.Windows nuget package.

**Comment by RobGallo** [comment]
UWP XAML apps run in App Containers. The UIA client API, which Axe.Windows uses to get accessible states and properties, cannot be called from App Containers. So, unfortunately, you will not be able to call Axe.Windows from your UWP unit test app.
However, Axe.Windows will work from a .Net Framework unit test project.

**Comment by benabbon** [comment]
Can you provide some examples on how to do that? 
I followed your instructions, created a .Net unit test project. Added Axe.windows (0.3.5-prerelease), Appium.WebDriver (4.1.1), and MSTest.TestFramework (2.0.0).
I'm able to launch the app, but the analyze() fails directly with this error: 
`        OpenQA.Selenium.WebDriverException: Unexpected error. Command not implemented: POST: /session/39D59AA2-0548-4924-85A9-C95E610F0A9A/frame
  Stack Trace: 
    RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
    RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    RemoteTargetLocator.DefaultContent()
    WebDriverInjectorExtensions.Inject(IWebDriver driver, IAxeScriptProvider scriptProvider)
    AxeBuilder.ctor(IWebDriver webDriver, AxeBuilderOptions options)
    WebDriverExtensions.Analyze(IWebDriver webDriver, IWebElement context)
`
I'm using the latest pre-release of WinAppDriver. When using the latest stable release, I got another error around lookup by tag not implemented. 

Also tried doing it using Config.Builder.ForProcessId as detailled in the readme, even if I'm not a fan of this solution because I can't include it in my tests directly, and need some weird mechanisms to detect the processId of the target App. Even with this, I'm unable to run the scan on the app with this error:
`ERROR Automation017: Fail to get the root element of a process(29640) : System.ArgumentNullException: Value cannot be null.\r\nParameter name: element\r\n   at Axe.Windows.Actions.Contexts.ElementContext..ctor(A11yElement element)\r\n   at Axe.Windows.Automation.TargetElementLocator.LocateRootElement(Int32 processId)`

**Comment by benabbon** [comment]
For the process issue, I managed to solve it, it was due to debug breakpoints changing the active window. The scan results are completely empty though, no output file while I used the A11yTest one.
Also, how do you suggest navigating in my app and do a fast pass on all my pages with the proposed readme way?

**Comment by benabbon** [comment]
Got it, I'll use the selenium application on the side, and have the fast pass as a test finalized. I'll give it a try and update the issue if it works as expected.
