### ISSUE TITLE
[General Question] Are SARIF outputs still supported?

### ISSUE THREAD

**Issue by benabbon** [microsoft/axe-windows#257]
## Are SARIF outputs still supported?

I'd like to know if there is away to generate SARIF files on failure along with a11ytest files. The entry is present in scan result output, but doesn't look like it gets populated.

If not, do you know a way to craft SARIF files from a11yTest ones?

I'd like to leverage a devops task that uploads SARIF files directly to the Accessibility tab for a better view of failures.

Thanks!

**Comment by AhmedAbdoOrtiga** [comment]
We don't support Sarif, and I don't think we have a way to convert a11yTest to Sarif.
I'm not sure also if we have a plan for that, but you always can submit a feature request and the team will will discuss it.

**Comment by benabbon** [comment]
Thanks for the info @AhmedAbdoOrtiga . I'll close the issue now and open a feature request if there is no way around it.
