### ISSUE TITLE
UIA HeadingLevel values are reported incorrectly

### ISSUE THREAD

**Issue by guybark** [microsoft/axe-windows#263]
**This was transferred from AIWin, but the root cause is in Axe.Windows** 

Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**
UIA HeadingLevel properties are not reported in the most helpful way to AIWin users.

**To Reproduce**
1. Go to the Windows Settings app System Sound page. 
2. Point the AIWin tool at the "Output" heading on the page. 
3. Check the reported UIA HeadingLevel property data, "Unknown(80052)".

**Expected behavior**
As listed at https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-heading-level-identifiers, a HeadingLevel property value of 80052 is "Heading level 2". As such, AIWin should say something like "Heading level 2, (80052)".

**Actual behavior**
By saying "Unknown(80052)", it's less likely that the AIWin user will learn the heading level of the UI of interest.

**Screenshots or .GIF**
![AIWin_HeadingLevel_Unknown](https://user-images.githubusercontent.com/14315611/71017879-3c847980-20ac-11ea-81ca-2e77444ef742.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909, OS Build 18363.535
 - Accessibility Insights for Windows Version: 1.1.1072.1
 - Target Application: Settings app in Windows.

**Additional context**

**Comment by DaveTryon** [comment]
Root problem here is a bug in the code that assigns human-readable names to heading levels.

**Comment by DaveTryon** [comment]
I guess Guy should be the one to close this out (even though it won't show in in AIWin until we pick up a newer version of Axe.Windows).

**Comment by DaveTryon** [comment]
@guybark, the fix for this is in our latest Canary build of AIWin: https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1138.01. Please regress and close when you get a chance. Thanks!

**Comment by adarshrema** [comment]
Hello @guybark, closing this as resolved. Please reopen if it regresses.
