### ISSUE TITLE
[BUG] UIA StyleId property values are always reported as "Unknown"

### ISSUE THREAD

**Issue by guybark** [microsoft/axe-windows#265]
**This was reported against AIWin, but the root cause is in Axe.Windows**

Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**
UIA StyleId properties are not reported in the most helpful way to AIWin users.

**To Reproduce**
1. Go to a Microsoft web page with semantic headings. For example, Office.com.
2. Point the AIWin tool to a heading on the page. For example, at Office.com, "Welcome to Office".
3. Use the AIWin tool to access the TextRange for the UI, via the TextChild patterm.
4. Check the reported UIA StyleId property data, "Unknown(70001)".

**Expected behavior**
As listed at https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-style-identifiers, a StyleId property value of 70001 is "A first level heading". As such, AIWin should say something like "Heading level 1, (70001)".

**Actual behavior**
By saying "Unknown(70001)", it's less likely that the AIWin user will learn the heading level of the UI of interest.

**Screenshots or .GIF**
![AIWin_StyleId_Unknown](https://user-images.githubusercontent.com/14315611/71019481-393ebd00-20af-11ea-943a-2168f99d5f65.png)

**Desktop (please complete the following information):**
- OS: Windows 10 1909, OS Build 18363.535
- Accessibility Insights for Windows Version: 1.1.1072.1
- Target Application: Settings app in Windows.

**Additional context**

**Comment by DaveTryon** [comment]
AIWin changes (requiring updated Axe.Windows) are at https://github.com/DaveTryon/accessibility-insights-windows/tree/DisplayStyleIdCorrectly

**Comment by DaveTryon** [comment]
The Axe.Windows fix is in place. The AIWin change will be added after we pick up the updated version of Axe.Windows (https://github.com/microsoft/accessibility-insights-windows/issues/682)

**Comment by DaveTryon** [comment]
I guess Guy should be the one closing this out

**Comment by ferBonnin** [comment]
@DaveTryon is there a way for Guy to verify this changes or do we need to wait for a release?

**Comment by DaveTryon** [comment]
@ferBonnin, @guybark, this will require an update to AIWin, which isn't slated to occur until we complete the changes to support .NET Core systems

**Comment by DaveTryon** [comment]
@guybark, the fix for this is in our latest Canary build: https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1138.01. Please regress and close when you get a chance. Thanks!

**Comment by adarshrema** [comment]
Hello @guybark, closing this as resolved. Please reopen if it regresses.
