### ISSUE TITLE
[BUG] EditSupportsOnlyValuePattern should return an error

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/axe-windows#27]
[Migrated from ai-win](https://github.com/microsoft/accessibility-insights-windows/issues/287), see full detail there

> The UIA spec (https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supporteditcontroltype) requires every edit control to support at least the Text control pattern. The Value pattern is supplemental. This rule should return an error.

> As I understand it, the rule fires when an edit control supports the value pattern but does not support the text pattern. The documentation says ITextProvider is required, while IValueProvider depends. The only thing wrong with the rule is how the outcome is reported. I believe failure instances should be shown as errors instead of uncertain.

**Comment by Sirisha-Kommushetty** [comment]
@RobGallo - Please comment and assign back to me

**Comment by Sirisha-Kommushetty** [comment]
Please update the release notes for Axe.Windows to callout the rule changes for reference.

**Comment by DaveTryon** [comment]
@karanbirsingh, can you please close this out? Thanks!
