### ISSUE TITLE
Structure rules should include IsContentElement/IsControlElement/pattern checks and increased unit test coverage

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/axe-windows#28]
[Migrated from ai-win](https://github.com/microsoft/accessibility-insights-windows/issues/282), see original post there

The [structure rules](https://github.com/Microsoft/accessibility-insights-windows/tree/master/src/AccessibilityInsights.Rules/Library/Structure) have the following gaps:
- they run on elements regardless of whether `IsControlElement` or `IsContentElement` is true. 
- unit test coverage is light on these rules
- in some cases, additional pattern guidance has been added in Microsoft documentation (example [here](https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supportspinnercontroltype)). Our rules do not use the pattern when selecting elements to test

Because these are best-practice rules (evaluated as either `Pass` or `Note`), the user impact is not too high if the rules are unnecessarily run or scoped too loosely. However, we should be as close to the docs as possible.

We should consider making a full pass through the [documentation](https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supportinguiautocontroltypes) to:
- ensure [content rules](https://github.com/Microsoft/accessibility-insights-windows/tree/master/src/AccessibilityInsights.Rules/Library/Structure/ContentView) and [control  rules](https://github.com/Microsoft/accessibility-insights-windows/tree/master/src/AccessibilityInsights.Rules/Library/Structure/ControlView) only test elements if `IsControlElement` or `IsContentElement` is true
- add unit tests for each class
- where appropriate, ensure rules only test elements if the appropriate pattern exists

**Comment by Sirisha-Kommushetty** [comment]
@RobGallo - Please comment and then assign back to me.

**Comment by Sirisha-Kommushetty** [comment]
This is low priority and can be investigated at a later point.

**Comment by Sirisha-Kommushetty** [comment]
closing this out.
