### ISSUE TITLE
[BUG] False positive for "The Name must not include the same text as the LocalizedControlType."

### ISSUE THREAD

**Issue by RobGallo** [microsoft/axe-windows#330]
## Issue

There are instances where the rule which detects control type strings within Name property strings may incorrectly return an error. For example, on a site for a taylor making a suit jacket, there could be and "_add a button_" button. In this case, the occurrence of the word "_button_" in the name is correct because it is not referring to the control type.

## Current state

We are keeping this bug open so users can report any other instances when they find a false-positive in this rule so we can understand better how to address it.
We welcome feedback for improving the heuristic that detects control type strings in the Name property.

### Suggested improvements

* **Only look for control type strings at the end of the name.** 
This would avoid double speaking. However, there were real-world instances we encountered where this wasn't always the case, e.g., "'table of definitions' table".

* **Only check for control type strings at the beginning and end of the name**. However, this will not catch other cases like "this is an image of a flower"

* **Check for commonly used phrases and the control type** for example: "this is a <control type>" or " this shows a <control type>"

We will continue to refine our approach so that this rule does not produce false positives. 

In the mean time, if you should encounter this error, please let us know in this bug.

The purpose of the rule is to avoid double rendering of the control type in accessible technologies such as screen readers. If the Name property contains a word or phrase which is a homonym of a control type string and which does not refer to the control's type, that may be an acceptable exemption to this rule.

**Comment by ferBonnin** [comment]
making a note of a new report of this issue with a button named "Button / Key"

**Comment by ferBonnin** [comment]
making a note of a new report of this issue with a group that had to have the Group name as part of it

**Comment by DaveTryon** [comment]
@juchampa, you flagged this as ready for work, but it's not clear what work should happen here. Moving back to needs investigation status

**Comment by chingucoding** [comment]
Out of curiosity, is there any future plan for this issue? Given that there was no traction in over 18 months now, maybe this can be closed?

**Comment by DaveTryon** [comment]
We aren't planning any additional work on this, so this issue is primarily informational
