### ISSUE TITLE
[BUG] Possible false-negative result for the rule "Children of off-screen element's must also be off-screen"

### ISSUE THREAD

**Issue by lennyomg** [microsoft/axe-windows#357]
## Issue

Possible false-negative result for the rule "Children of off-screen element's must also be off-screen"

Accessibility Insights show the error mentioned above for a WPF app which has a list box with complex elements and some of the elements are scrolled to outside the visible area. It happens because the ListBox/ListView control marks top-level elements `IsOffscreen = true`, but don't do it for all sub-elements. In other words, it happens that the element outside the visible area has `IsOffscreen = true`, but all its children have `IsOffscreen = false`.

With the default scrolling behavior, it is not possible to select an element without making it visible (that immediately makes the element `IsOffscreen = false`). So, I don't see any wrong behavior in WPF.

## To Reproduce

```
<Window x:Class="ChildrenOffscreenIssue.MainWindow" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:collections="clr-namespace:System.Collections;assembly=mscorlib"
        xmlns:system="clr-namespace:System;assembly=mscorlib" mc:Ignorable="d" Title="MainWindow" Height="450"
        Width="400">
    <ListBox>
        <ListBox.ItemsSource>
            <collections:ArrayList>
                <system:String>item 01</system:String>
                <system:String>item 02</system:String>
                <system:String>item 03</system:String>
                <system:String>item 04</system:String>
                <system:String>item 05</system:String>
                <system:String>item 06</system:String>
                <system:String>item 07</system:String>
                <system:String>item 08</system:String>
                <system:String>item 09</system:String>
                <system:String>item 10</system:String>
                <system:String>item 11</system:String>
                <system:String>item 12</system:String>
                <system:String>item 13</system:String>
                <system:String>item 14</system:String>
                <system:String>item 15</system:String>
            </collections:ArrayList>
        </ListBox.ItemsSource>
        <ListBox.ItemTemplate>
            <DataTemplate>
                <StackPanel>
                    <TextBlock Text="{Binding}" />
                    <Button Content="{Binding}" />
                </StackPanel>
            </DataTemplate>
        </ListBox.ItemTemplate>
    </ListBox>
</Window>
```

## Expected behavior

Accessibility Insight tool mustn't report the error for elements that have a parent with IsOffscreen = false.

## Actual behavior

Accessibility Insight tool reports the error for elements that have a parent with IsOffscreen = false.

## Screenshots

![image](https://user-images.githubusercontent.com/1433092/80152500-a20fd780-8570-11ea-9ded-eda47adf0fa7.png)

## Desktop

 - OS: Windows 10 1909
 - Accessibility Insights for Windows Version: 1.1.1198.01
 - Target Application: WPF / .NET 4.6.1

**Comment by RobGallo** [comment]
We agree this is a false positive. The rule is removed in PR #369.
