### ISSUE TITLE
[General Question] 

### ISSUE THREAD

**Issue by luvukr** [microsoft/axe-windows#370]
## AutomationId is unavailable.

**HierarchyNodeViewModel.cs** Line No:- 277 
```
this.Children = (from c in ce.Children
                                 select new HierarchyNodeViewModel(c, showUncertain, isLiveMode)).ToList();
```

Why is automationId unavailable at this point. I tried it for those elements which do have automationId. Is it on purpose?. If yes, Can you let you know at which point AutomationIds get set for the elemnet. I am trying to get `AutomationElement` equivalent of `A11yElement`.

**Comment by DaveTryon** [comment]
Hi, @luvukr! Your code snippet is from the accessibility-insights-windows repo, not the axe-windows repo, but I'll go ahead and try to answer it here anyway.

Fetching UIAutomation properties requires inter-process communication (IPC), which makes it expensive. The [A11yElement](https://github.com/microsoft/axe-windows/blob/master/src/Core/Bases/A11yElement.cs) object is initially created with just enough information to create a placeholder, then the specific properties are requested at a later time. In the code you cited, the populating the properties is deferred to when the properties are rendered in the UI. There are multiple things that can trigger the population of the data. Just for illustration, I modified the **HierarchNodeViewModel.cs** code as follows--AutomationID's get logged to the debugger as you move the selection window:

```
                this.Children = (from c in ce.Children
                                 select new HierarchyNodeViewModel(c, showUncertain, isLiveMode)).ToList();
                ce.PopulateAllPropertiesWithLiveData();
                Debugger.Log(1, "Sample", "AutomationId = " + ce.AutomationId + "\n");
```

At this point, I need to point out that while the `A11yElement` class is publicly visible, it's not considered a documented interface to Axe.WIndows. We have no current plans to change it, but if/when such future changes were to occur, any dependent code could suddenly fail to compile or fail to run as expected, with the only warning coming from the PR that committed the change.

I'm marking this issue as resolved and assigning it back to you. Please close it out at your convenience. Thanks!

**Comment by luvukr** [comment]
Thanks @DaveTryon. I have a bit of an idea now with this explanation.
