### ISSUE TITLE
Accessing Apps like electron

### ISSUE THREAD

**Issue by luvukr** [microsoft/axe-windows#379]
## Your question here
How does `A11yAutomation.GetUIAutomationObject().PollForPotentialSupportedPatterns()` and `                A11yAutomation.GetUIAutomationObject().PollForPotentialSupportedProperties()` poll internally?

My use case is to inspect elements from an electron app. Using **Accessibility insight for window** tool, I can see the props in real-time but I want to understand that when an electron app internally loads a webpage, how does Windows get access to the dom structure?

**Comment by pownkel** [comment]
Hi Sumit, thank you for your interest in Accessibility Insights! For Electron applications, recent versions of Windows 10 (1903 and later) convert the IAccessible2 data provided by Chromium into UI Automation data, which is what axe-windows uses to inspect elements.

However, keep in mind that Electron are Web based frameworks, so using Web accessibility standards and rules will provide more actionable results. We do not currently provide a way to test Electron apps with web accessibility rules, but we do have an [open feature request](https://github.com/microsoft/accessibility-insights-web/issues/558) for this functionality in the repository for our chrome extension. If this is something you'd like to see in the future, feel free to upvote the feature request!

Does that help answer your question?

**Comment by luvukr** [comment]
Sorry for the delayed reply @RobGallo @pownkel I used both of your suggestion and it worked. Thanks a lot to you both. But there is a glitch sometimes, It doesn't broadcast the elements just the native window of the app(teams) but all of a sudden It will start giving the hierarchy. I am unable to find out the root cause of the issue of why sometimes it does not give up the hierarchy.

**Comment by RobGallo** [comment]
@luvukr  
Axe.Windows is not intented to be used to analyze Electron-based apps; so the situation you've described is not one we've investigated. You can inspect the issue using the code in this repo. Let us know if there's something we could improve. Or even better, you could submit a pull request to the repo. Thanks, Rob
