### ISSUE TITLE
[BUG] BoundingRectangleNotNull fails to properly exclude System menu bars if the text is non-English

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/axe-windows#402]
## Describe the bug

We exclude certain menubars/items from the BoundingRectangleNotNull check [here](https://github.com/microsoft/axe-windows/blob/f2adece0a4ed0c1c68358fdbcec6f3a620b255b4/src/Rules/Library/BoundingRectangleNotNull.cs#L30).

In a non-English application, the automation name is localized so the 'System' string check doesn't work. We should consider solely relying on the automation id so that the automation names don't have to be identical.

**Comment by ferBonnin** [comment]
@RobGallo marking this as resolved, reopening and assigning to Karan to review and close
