### ISSUE TITLE
AIWin unexpectedly reports failures with WPF DataGrid's which contain cells with text duplicated between cells

### ISSUE THREAD

**Issue by guybark** [microsoft/axe-windows#417]
Create a new WPF app using .NET Framework 4.8, and add a DataGrid to it. Give the column headers unique names, and populate the cells with some text which is duplicated between cells. Or just grab the demo app I built at https://account79.visualstudio.com/WPFDataGridDuplicateCellNames.

Run the app and point AIWin to the DataGrid.

Result: AIWin reports a failure relating to cells having duplicate Name and LocalizedControlTypes.

Expected: No failure should be reported given that the cells support the UIA GridItem and TableItem patterns, as as such, screen readers can announce the row and column information associated with the cells. This means customers can learn the unique meaning of each cell, even when multiple cells contain the same text.

 - OS: Windows 10 1909
 - Accessibility Insights for Windows Version: 1.1.1248.1
 - Target Application: Test WPF app targeting .NET Framework 4.8, containing a DataGrid.

**Comment by karanbirsingh** [comment]
@guybark Thanks for filing the issue - I wasn't able to download the demo app due to permission issues. Do you mind either modifying the permissions, or uploading the a11y test file to this issue? You may need to rename it to a zip file if you upload to GitHub.

**Comment by guybark** [comment]
Sorry for the delay in sorting this out. How about this, [WPFDataGridDuplicateCellNames](https://github.com/guybark/WPFDataGridDuplicateCellNames).

**Comment by RobGallo** [comment]
Addressed in PR #421

**Comment by adarshrema** [comment]
In queue to be picked up in the next Axe.Windoes and Accessibility Insights for Windows releases.

**Comment by DaveTryon** [comment]
Hi, @guybark! This has been released to production at https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1334.02. Please regress as your convenience. Thanks!

**Comment by guybark** [comment]
I've verified the failure is no longer reported in my test app with the duplicated DataGrid cell text, using AIWin 1.1.1334.2. Thanks for making the change.
