### ISSUE TITLE
[BUG] Adjacent identical hyperlinks should raise a warning instead of an error

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/axe-windows#42]
**Describe the bug**
The rule `Focusable sibling elements must not have the same Name and LocalizedControlType` fails when there are two adjacent Hyperlink elements. Hyperlinks should be excluded from this rule and moved into a warning based on the rationale given [here ](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-link.html)(`Best practice is that links with the same destination would have the same descriptions, but links with different purposes and destinations would have different descriptions`).

**Comment by karanbirsingh** [comment]
Download, rename to feedback.a11ytest, and open in Accessibility Insights for Windows to see repro:
[feedback.zip](https://github.com/microsoft/axe-windows/files/3242403/feedback.zip)

**Comment by DaveTryon** [comment]
Closing this out
