### ISSUE TITLE
[BUG] AIWin reports an unexpected failure on a short WPF separator  

### ISSUE THREAD

**Issue by guybark** [microsoft/axe-windows#432]
## Describe the bug

A product shows a short vertical separator, and AIWin reports its bounding rectangle as being too small.

**To Reproduce**
1. Create a new WPF app targeting .NET Framework 4.8.
2. Add a very short short separator.
3. Run AIWin FastPass against the app.

## Expected behavior

AIWin reports that there are no failures in the programmatic representation of the separator. 

## Actual behavior

AIWin reports that the BoundingRectangle property of the separator must represent an area of at least 25 pixels.

## Desktop (please complete the following information):

 - OS: Windows 10 2004.
 - Accessibility Insights for Windows Version: 1.1.1248.1

## Additional context

The separator in the product provide visual assistance to some customers that two text strings are distinct, but it's not essential. As such AIWin should not be calling this a failure. Given that BoundingRectangleSizeReasonable() already seems to not report this failure for text elements, perhaps that could be extended to not report it for separators too?

**Comment by DaveTryon** [comment]
This has been merged into AIWin and will appear in the next Canary build. I'll resolve it once the build has been published.

**Comment by DaveTryon** [comment]
@guybark, this change has been included in the Canary release of AIWin at https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1354.01. Please regress and close out when you can. Thanks!

**Comment by guybark** [comment]
Verified as fixed with AIWin 1.1.1360.1. Thanks for addressing this!
