### ISSUE TITLE
Add how-to-fix info for 'custom' DataGridCell behavior in old .NET Framework versions

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/axe-windows#441]
This issue tracks adding more actionable guidance for the DataGridCell issue in https://github.com/microsoft/accessibility-insights-windows/issues/931. 

It was fixed by directing the user to either update to .NET 4.7.1 or to use accessibility switches. This DataGridCell issue (alongside some other updates) was explicitly called out in the .NET 'What's new in accessibility' [documentation here](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility#whats-new-in-accessibility-in-net-framework-471).

If axe-windows detects this error, we should suggest updating/accessibility switches in the tool itself.

Details:
- create a new failing rule that targets DataGrids with this issue (can look for custom control type/localized control type, wpf framework, and class name)
- include how-to-fix information that mentions the suggested fix from above & how-to-fix information from `LocalizedControlTypeIsNotCustom`
- update the behavior of LocalizedControlTypeIsNotCustom: https://github.com/microsoft/axe-windows/blob/95b5fe9f41b9e9f8c5b9b7ddc8534451ca63f2f4/src/Rules/Library/LocalizedControlTypeIsNotCustom.cs#L16 to exclude testing elements that are tested by the new rule

An alternative approach would require updating our how-to-fix mappings to be chosen dynamically from within a rule, rather than a 1:1 mapping from a rule to HowToFix entities. When discussing with Rob, the new-rule approach seemed more aligned with the existing codebase.

We should also check whether this rule has an associated how-to-fix link. Based on that, it might make sense to add or update the doc with a note about this issue.

**Comment by RobGallo** [comment]
Addressed in PR #478

**Comment by DaveTryon** [comment]
@karanbirsingh, this is in the build at https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1467.01. Please validate & close at your convenience 😃
