### ISSUE TITLE
[bug] Exception being thrown while creating a scanner using default parameters inside a UWP app

### ISSUE THREAD

**Issue by chingucoding** [microsoft/axe-windows#460]
## Is your feature request related to a problem? Please describe.

Not really a feature, but writing test results does take some time. Usually it doesn't really make a difference, but if there are hundreds of test runs, this might make a difference.
## Describe the solution you'd like

This is where it becomes a bit difficult. Currently an empty path is being replaced with a default path, setting the FileFormat to "None" still creates files (I think). The scanner factory could expose a function that skips the creation of the file helper entirely, something like "BuildNoFileLogging". However having the configuration object still have the filepath and fileformat property might look a bit weird.

## Describe alternatives you've considered

None yet as this isn't a big issue. It would be nice to have.

**Comment by DaveTryon** [comment]
Good news, @chingucoding! This feature already exists. All you need to do is build the config file without ever specifying an output type or output directory. This will tell the scanner to bypass creating the disk file and return results only via the ScanResults object returned from IScanner.Scan();

If you refer to [AutomationReference.md](https://github.com/microsoft/axe-windows/blob/9610092732f1fa512adb346527e85db8a77b6210/docs/AutomationReference.md), you'll see this sample for the config builder:

```
                var config = Config.Builder.ForProcessId(testProcess.Id)
                    .WithOutputFileFormat(OutputFileFormat.A11yTest)
                    .WithOutputDirectory(outputDir)
                    .Build();
```

Remove the calls to the WithOutput* methods, and you're done:

```
                var config = Config.Builder.ForProcessId(testProcess.Id)
                    .Build();
```

Scanning may still take some time since UI Automation involves a lot of IPC, but you won't lose any time generating the A11yTest file.

Thanks for your ongoing support of Axe.Windows! Please close this issue once you've had a chance to confirm that this works as described.

**Comment by chingucoding** [comment]
You would think that that is the case, funnily, it is not. If you paste the following in a UWP project (yes, UWP as the sandbox will crash us since we write where we shouldn't), you will notice that the stack get's pretty deep.

```c#
var processId = ProcessDiagnosticInfo.GetForCurrentProcess().ProcessId;
var _config = Config.Builder.ForProcessId((int)processId).Build();

var _scanner = ScannerFactory.CreateScanner(_config);
```

A lot of the code related to file writing despite file option set to none. Of course this is almost nothing performance wise since IPC is the main bottle neck, but maybe for simplicity, we could do a "end fast" if the file format "None" is chosen?

**Comment by DaveTryon** [comment]
Interesting! We were looking at the code that runs during the call to IScanner.Scan(), but this is throwing before we get that far. This is throwing while we're still creating the scanner:

```
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Axe.Windows.SystemAbstractions.SystemIODirectory.CreateDirectory(String path) in src\SystemAbstractions\Concretions\SystemIODirectory.cs:line 12
   at Axe.Windows.Automation.OutputFileHelper..ctor(String outputDirectory, ISystem system) in src\Automation\OutputFileHelper.cs:line 45
   at Axe.Windows.Automation.Factory.CreateOutputFileHelper(String outputDirectory) in src\Automation\Factory.cs:line 23
   at Axe.Windows.Automation.ScanToolsBuilder.WithOutputDirectory(String outputDirectory) in src\Automation\ScanToolsBuilder.cs:line 21
   at Axe.Windows.Automation.ScannerFactory.CreateScanner(Config config) in src\Automation\ScannerFactory.cs:line 22
```

The problem occurs in https://github.com/microsoft/axe-windows/blob/master/src/Automation/OutputFileHelper.cs#L45, where we ensure that the output folder exists, which isn't necessary if we're not producing any output.

This is definitely a bug in our code. The workaround is to specify an outputDirectory that already exists (like a desktop or the folder of the currently running process), so it isn't a particularly high priority. I'll reclassify this as a bug and put it into the triage list. I can't offer a timetable of when we'd have a fix in place.

If you'd like to speed up the process, please feel free to submit a PR. It might make sense to add a private readonly member to save the ISystemIODirectory object that gets validated at https://github.com/microsoft/axe-windows/blob/master/src/Automation/OutputFileHelper.cs#L34, then move the code from https://github.com/microsoft/axe-windows/blob/master/src/Automation/OutputFileHelper.cs#L44 to the top of `OutputFileHelper,GetNewA11yTestFilePath`. I suspect that some mocks in unit tests would also need to be updated to reflect the change, but it should be pretty straightforward.

**Comment by chingucoding** [comment]
Thanks for the update!

> If you'd like to speed up the process, please feel free to submit a PR.

Sure, I will create a PR for this soon! I will probably use a different solution to also not break when scanning then.

**Comment by RobGallo** [comment]
I have created PR #462  to address the issue. The fix is a little different: it moves the exception into a place where it will still be thrown, but only if output files are requested.

**Comment by chingucoding** [comment]
@RobGallo how would this play with #461? One of us probably has to do merge after one of the PRs gets merged into master, right?
