### ISSUE TITLE
[Feature request] Test Axe.Windows scanning against a UWP app and if so how?

### ISSUE THREAD

**Issue by chingucoding** [microsoft/axe-windows#463]
## Test Axe.Windows scanning against a UWP app and if so how?
Continuing conversation from #460 

There are few different ways how that could be achieved. The key issue is that a UWP app needs installation. The possibilities are:
- Sideload app and try to clean up after tests
  - If something goes wrong, the machine can be left in a bad state
- Have the test run be optional, if it finds the app it runs, otherwise tests are skipped
- Similiar to the point above: Only run those tests locally
  - Issue is that in that case tests might not be run and all

Since the main thing to check is whether it is working with a UWP UI, not the UWP app, another option would be to use XAML Islands. That way, we can run an exe file that in turn starts a UWP UI that we can scan against. That way, we would be able to test against UWP UIs (and as such UWP apps) without having to deal with installation and clean up of a UWP app.

However setting up XAML islands isn't the easiest after all and the root window of the app still reports itsself as WPF framework, only the content does report itsself as using "XAML" (UWP):

![image](https://user-images.githubusercontent.com/16122379/98415187-162d4b00-207d-11eb-85cd-7fdd9b7dfa66.png)

So at the end of the day, this mostly boils down to what are the costs of getting it to work, and what is there to gain to test against a UWP app or UWP UIs.

**Comment by adarshrema** [comment]
@chingucoding, thank you for your continued interest and for this feature request. Given our current priorities unfortunately this is not something we will be able to take on now. However, if you are interested in contributing, please let us know when you have a sample working and we will be happy to link to it from the repo.

**Comment by chingucoding** [comment]
If I find the time and get something running and working, I'll post a comment here, however I can't promise anything.
