### ISSUE TITLE
[BUG] - Manage Axe-Windows dependencies

### ISSUE THREAD

**Issue by Sirisha-Kommushetty** [microsoft/axe-windows#47]
**Describe the bug**
  When I first assembled the automation package, I included all of the dependencies (Sarif, Netwonsoft, and some System.* assemblies) directly into the package. I did it largely out of ignorance, because it seemed logical to have the files all together in one place. That also helped the PowerShell cmdlet story to flow easily. As it turns out, the recommended way to manage dependencies is simply to include them as dependencies, and allow the resolution to be handled by the app. Now that PowerShell cmdlets are going away, maybe it’s time to align with the recommended dependency handling. Here are a couple of links discussing this issue:
  https://stackoverflow.com/questions/28229892/nuget-package-dependencies
  https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution

  This probably wouldn’t be part of the API spec, but it seems like we ought to have a clear story here before we get to the 1.0 release.

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version:
 - Target Application: [e.g. Chrome, Wildlife Manager]
 - Target Application Version: [e.g. 22]

**Additional context**
Priority requested -

**Comment by Sirisha-Kommushetty** [comment]
Based on my convo with Rob and Dave, we'll accommodate this for 0.3.0 release and call out any potential breaking changes.

**Comment by RobGallo** [comment]
Fixed in PR #86

**Comment by DaveTryon** [comment]
@Sirisha-Kommushetty, please determine if we can close this out. Thanks!

**Comment by Sirisha-Kommushetty** [comment]
Thanks for getting this done!
