### ISSUE TITLE
[BUG] “The Name must not include the same text as the LocalizedControlType” error while using password input control in 'Old Edge' in a Windows app

### ISSUE THREAD

**Issue by adarshrema** [microsoft/axe-windows#471]
Password input control in Old/ Classic Microsoft Edge (framework id: MicrosoftEdge) hosted in a Windows Universal App fails “The Name must not include the same text as the LocalizedControlType” rule. 

## Actual behavior
When the password input control from Old Edge is hosted in a Windows Universal App, the word 'password' is repeated in Name and LocalizedControlType resulting in violation of “The Name must not include the same text as the LocalizedControlType” rule. When the same HTML is hosted on Web, this rule is not violated as the LocalizedControlType is generated as 'edit'. This is a limitation of old Edge and this behavior will continue as long as the framework is use and the bug cannot be fixed.

## Expected behavior
Update the rule so users do not encounter this as an error when password input control from Old Edge is hosted in a Windows Universal App. 

## Fix
If the framework is “MicrosoftEdge”, if the control type is Edit, and if IsPassword is true, the rule that tests to make sure that the Name and LocalizedControlType to be different will not be checked.

**Comment by adarshrema** [comment]
Extending this to Email control in Old Edge as well as the same issue is encountered in that scenario. Fix:
If the framework is “MicrosoftEdge”, if the control type is Edit, and if the LocalizedControlType is password or email, the rule that tests to make sure that the Name and LocalizedControlType to be different will not be checked.

**Comment by chingucoding** [comment]
Is it fine if I work on this issue?

**Comment by chingucoding** [comment]
@RobGallo Didn't #480 address this exact issue and thus, this issue can be closed?

**Comment by RobGallo** [comment]
@chingucoding 
Yes it did. Our practice is to mark bugs as resolved, which I forgot to do yesterday, until they are included in an actual release, at which time we close them. Thanks!

**Comment by chingucoding** [comment]
Ah okay, thanks for the explanation.

**Comment by DaveTryon** [comment]
@adarshrema, this is fixed in the latest Canary bits (https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1467.01). Please validate/close at your convenience. Thanks!

**Comment by adarshrema** [comment]
Validated in canary.
