### ISSUE TITLE
[BUG] Control should not support table pattern error on SysListView32

### ISSUE THREAD

**Issue by RobGallo** [microsoft/axe-windows#483]
## Describe the bug

The table pattern is implemented on Win32 list views (class "SysListView32"), but the user has no way to remove it and the platform is no longer supported.

**To Reproduce**

Occurs for the CList class when building an app using MFC. We don't have a specific example since the problem was discovered using an a11ytest file and the app being tested belongs to a third party.

## Expected behavior

The error should not be thrown

## Actual behavior

An error is thrown.

**Comment by DaveTryon** [comment]
@RobGallo, this is fixed in the current Canary build: https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1467.01. Please validate and close at your convenience. Thanks!

**Comment by RobGallo** [comment]
Fixed in PR #484
