### ISSUE TITLE
[BUG] Error in a control in an app built with MFC when its name property contains 'Microsoft.' or 'Windows.'

### ISSUE THREAD

**Issue by adarshrema** [microsoft/axe-windows#485]
This was reported for an in-house app built using MFC by a third-party OEM. The problem was reported using an a11ytest file.
When the Name property of a Control contains 'Microsoft.' Or 'Windows.', “The Name property must not contain its class name”. error is thrown. 
This is a valid use of these proper nouns in the name of a package that ships with the third-party device. The rule is designed to catch a specific problem in some .Net controls where instead of adding meaningful names to controls, .Net Framework automatically adds the class names. The names always follow the pattern 'Microsoft.*' or 'Windows.*'.
Fix: Do not run this rule in the Win32 Framework.

Expected behavior
The error should not be thrown

Actual behavior
An error is thrown.

**Comment by DaveTryon** [comment]
@adarshrema, the key issue here is the content of the control. In this specific scenario, the rule does not apply. As explained in email, I don't think any code changes are necessary other than the rule description change that occurred in #486

**Comment by adarshrema** [comment]
Keeping this open to confirm if the issue would be addressed by changes in #[486](https://github.com/microsoft/axe-windows/pull/486) or if additional work is needed to exclude applicability of the rule based on framework of the app being tested.

**Comment by adarshrema** [comment]
Fix: Do not run the “The Name property must not contain its class name” rule in the Win32 Framework.
