### ISSUE TITLE
[BUG] Big Memory Leak

### ISSUE THREAD

**Issue by xWSWx** [microsoft/axe-windows#487]
## Describe the bug

Axe.Windows.Actions.SelectAction has memory leak

**To Reproduce**

1. Create new project by VS 
2. Install Axe.Windows nuget package v1.0.4
3. Write little code (WPF for example)

![image](https://user-images.githubusercontent.com/29701338/103075174-ac054100-45fd-11eb-98c5-7967dfcce71d.png)

4. Run
5. Wait for 3 hours

## Expected behavior

used memory has stable value

## Actual behavior

memory leak was detected

## Screenshots or .GIF

Sorry for the localized screenshot, but i hope it help
![image](https://user-images.githubusercontent.com/29701338/103074666-afe49380-45fc-11eb-9585-35679487267a.png)

## Desktop (please complete the following information):

 - OS:  Windows 10 2004
 - Axe.Windows version: 1.0.4
 - Target Application: no target

## Additional context

I studied the Axe.Windows source code, but not found your mistake
How can i fix memory leak myself? or i have to wait your fix?

P.S. Otherwise your library helps me a lot. thx!

**Comment by karanbirsingh** [comment]
@xWSWx thanks for the interest in the library! Sorry for the delay.

Several of the classes in Axe.Windows (like `SelectAction`) include unmanaged resources and implement the [`IDisposable` pattern](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/using-objects); explicit action to release resources (via `using`, `Dispose()`, explicit `SelectAction.Clear...()`, etc) can help. Rob's [response](https://github.com/microsoft/axe-windows/issues/481#issuecomment-744720578) to this question has more details.

At the moment we primarily maintain support for the APIs documented in the [Automation package](https://github.com/microsoft/axe-windows/blob/master/docs/AutomationReference.md). Depending on your scenario you might look at the [code there](https://github.com/microsoft/axe-windows/tree/master/src/Automation) either for direct use or reference. The APIs elsewhere in Axe.Windows are primarily for internal use from Accessibility Insights for Windows.

**Comment by xWSWx** [comment]
Thank you! I need a few days of time (it's a holiday week in my country now). I will definitely give you feedback after
