### ISSUE TITLE
[General Question] Average/approximate release schedule

### ISSUE THREAD

**Issue by chingucoding** [microsoft/axe-windows#526]
## What is the aimed/average/approximate release schedule for Axe.Windows?

I am working on intergrating Axe.Windows into the WinUI test suite (https://github.com/microsoft/microsoft-ui-xaml/pull/3764) and encountered issue due to the different way of handling dependencies (self hosted instead of NuGet). That left me wondering how often Axe.Windows gets a new release and how often this dependency would have to be updated manually.

PS: Love Axe.Windows; Feel free to close this issue after answering!

**Comment by lisli1** [comment]
@chingucoding, we don't have a regular release schedule. We tend to release new versions when rules are changed or bugs fixed.

I will close this issue per your suggestion but feel free to reopen it if you have follow-up questions.

**Comment by chingucoding** [comment]
Thanks for the answer @lisl1, nothing else to add/ask from my side.
