### ISSUE TITLE
[BUG]  when Narrator is on and scan mode is disabled, PreviewKeyDown event by pressing "Narrator+Enter" cannot be triggered whereas “Enter” or “Space” can. 

### ISSUE THREAD

**Issue by Leslie1Yang** [microsoft/axe-windows#543]
Please check whether the bug has [already been filed](https://github.com/Microsoft/axe-windows/issues).

## Describe the bug

When the Narrator is running, the behavior of RoutedEvent or KeyEvent are different. For example, we can press space to trigger the ckb_Click event without Narrator is running but we can’t do it by pressing Narrator+Enter or Space in scan mode to trigger the ckb_Click event. We’d like to know the reason behind since we have lots of customized user controls depending on this kind of event to complete the UI flow.

Same as the PreviewKeyDown event of a Button, we can press enter/space to trigger the PreviewKeyDoen event without Narrator is running but we can’t do it by pressing Narrator+Enter or Space in scan mode to trigger the btn_PreviewKeyDoen Click event. 
Therefore, we wanna know if there is a way to trigger PreviewKeydown Event when Narrator is running, the customized user control we designed has to be done with this event handler. Kindly check for us.

## Expected behavior

Narrator+Enter can trigger the event when Narrator is on and scan mode is disabled

## Actual behavior

only enter or space can trigger the event when Narrator is on and scan mode is disabled

![1](https://user-images.githubusercontent.com/80501344/111256537-4486ec80-8654-11eb-9ed5-b62d211f7f78.png)
![2](https://user-images.githubusercontent.com/80501344/111256544-481a7380-8654-11eb-8436-c09e44afb029.png)
[WpfAppTestNarrator.zip](https://github.com/microsoft/axe-windows/files/6146144/WpfAppTestNarrator.zip)

**Comment by karanbirsingh** [comment]
Hi Leslie, it seems like this question is closer to Narrator behavior or the .NET framework, which are separate from the axe-windows ruleset. We aren't the best folks to help with this; I see you have an open thread with eDAD, who may be better equipped to dig into this. I'm closing this issue for now, but feel free to let us know if we've missed some context about axe-windows rules. Thanks!
