### ISSUE TITLE
[Feature Request] Warn users when application is written in a Java framework that doesn't provide UIA information

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/axe-windows#554]
## Is your feature request related to a problem? Please describe.
When users test Java applications that don't provide meaningful UIA information (IntelliJ is an example), Axe.Windows & Accessibility Insights for Windows can show 0 errors. However, the UIA tree will show that very little UIA information was exposed. See this [FAQ question](https://accessibilityinsights.io/docs/en/windows/reference/faq/#can-i-use-accessibility-insights-for-windows-on-a-windows-app-written-with-java). Depending on how robustly we can detect these scenarios, it would be nice to add some warning, test result, or info in the application that explains this scenario to the user and encourages manual NVDA / JAWS testing.

One entry point could be using the classname to identify the framework. But maybe there are other solutions that use heuristics like empty UIA trees.

## Describe the solution you'd like
A user who encounters this situation should be given information about it inside the library/application.

## Describe alternatives you've considered
Currently users either:
- see the 0 errors and assume nothing is wrong, or
- see the empty UIA tree and need to debug / find more information

## Additional context
I'm not sure how "sure" we can be. We've seen this happen with the SunAwtFrame classname a few times, but I haven't explored whether it's possible to add UIA support a different way while maintaining that framework.

**Comment by chingucoding** [comment]
A way to somewhat detect this would be to have the UIA tree at least contain a certain amount of elements, e.g. a window that just has 2 elements is very likely to be entirely inaccessible since nothing is exposed.

**Comment by RobGallo** [comment]
I believe this feature request to have been address by PR #558

**Comment by karanbirsingh** [comment]
released in https://github.com/microsoft/axe-windows/releases/tag/v1.0.7
