### ISSUE TITLE
[BUG] Remove rule: An element of the given ControlType must not support the Table pattern.

### ISSUE THREAD

**Issue by RobGallo** [microsoft/axe-windows#566]
## Describe the bug

We will remove the rule ControlShouldNotSupportTablePattern because we have agreed with the UIA team that this rule is not necessary and produces false positives. Many UI Frameworks do not follow the documentation, creating issues application developers can't fix. And most developers seem to view lists with columns as the appropriate cognitive model for many types of data, rather than tables; so they conceive of their UX as lists with tabular characteristics.

The [documentation on the list control](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-supportlistcontroltype) should soon be updated to reflect this change. But we have agreed to make the change now to unblock developers.

**Comment by RobGallo** [comment]
This issue is resolved in PR #567

**Comment by karanbirsingh** [comment]
released in https://github.com/microsoft/axe-windows/releases/tag/v1.0.7
