### ISSUE TITLE
[BUG] Allow RadioButton to implement TogglePattern

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/axe-windows#590]
## Describe the bug

The rule https://github.com/microsoft/axe-windows/blob/a23dda60ec3784ab5b53a7d6f3484a1836a815fa/src/Rules/Library/ControlShouldNotSupportTogglePattern.cs#L13 prohibits radio buttons from implementing the toggle pattern. This is in line with the UIA documentation [here](https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/ui-automation-support-for-the-radiobutton-control-type#required-ui-automation-control-patterns). After some offline conversation with Rob+others, we feel it's more accurate to say that while it's rarely a good idea to implement the TogglePattern, doing so doesn't seem to impede the accessibility of the control. This bug is to relax or remove the rule so that radio buttons that do implement the toggle pattern aren't flagged by Axe.Windows. We are also reaching out to the docs owners to suggest accompanying updates there.

**Comment by chingucoding** [comment]
Can I take a look at this issue?

**Comment by DaveTryon** [comment]
@chingucoding, I'm not sure we know exactly what we want to do here. My guess is that we'll downgrade the rule from `ErrorCode.Error` to `ErrorCode.Warning`, although that's not 100% certain. Please feel free to create a PR against that assumption and I'll assign the issue for triage (we normally triage these issues on Mondays, so the PR might sit idle for a few days before we know for sure what our strategy will be on this).

**Comment by chingucoding** [comment]
Ah I see, my "instinct" would have been to just ignore the RadioButton control from this rule and leave it as an error. Alternatively, what about forking this rule into two rules:
1. Controls that DEFINITELY should not support togglepattern -> Error
2. Radiobutton that should not support the toggle pattern but is also okay if it supports toggle pattern -> Warning

**Comment by DaveTryon** [comment]
@chingucoding, that was my first thought, as well. Looking at this rule's [Condition](https://github.com/microsoft/axe-windows/blob/main/src/Rules/Library/ControlShouldNotSupportTogglePattern.cs#L32), though, only applies to `RadioButton` elements, so the decision tree collapses to just changing the [ErrorCode](https://github.com/microsoft/axe-windows/blob/main/src/Rules/Library/ControlShouldNotSupportTogglePattern.cs#L20) to a warning (and updating appropriate tests).

We'll have to wait and see what comes out of the triage discussion.

**Comment by chingucoding** [comment]
Ah I see, that makes sense. I'll create a PR and we'll see what the next triage discussion decides.

**Comment by DaveTryon** [comment]
@chingucoding, we discussed this today and decided that we want to remove this rule instead of making it a warning. Please feel free to submit an appropriate PR is you wish. Thanks!

**Comment by DaveTryon** [comment]
Thanks, @chingucoding! Your PR has merged and will be in tomorrow morning's build. We'll assign it back to @karanbirsingh for closing once the build is out

**Comment by chingucoding** [comment]
Great. thanks for the update @DaveTryon ! On a different note, is it worth pointing out in the contributions guideline or readme that bugs will be closed once a new build is out instead of being closed once the PR is merged?

**Comment by DaveTryon** [comment]
That's an interesting point about the contributions guideline, @chingucoding. In actual practice, issues get closed at different points, depending on the nature of the issue. There are 3 points where we would typically consider closing an issue:

1. After the change is incorporated into a signed build
2. After the change is incorporated into the published NuGet package
3. After the change is incorporated into the AIWin Canary release channel

I'll bring this up with the team to see if we want to try to clarify this in the docs.

**Comment by chingucoding** [comment]
Sweet, thank you! On a different note, would it make sense indicating the usage of semantic commit messages in this repo? (sorry for hijacking this issue for this)
