### ISSUE TITLE
[BUG] Rules descriptions is confusing

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/axe-windows#617]
## Describe the bug

Rules description file now uses new severities. It took me several minutes to find the definition of _Open_ and _Note_ and this new definitions might not be clear for our users or might add additional cognitive load

**To Reproduce**

1. Go to https://github.com/microsoft/axe-windows/blob/main/docs/RulesDescription.md
2. read the rules' severities

## Expected behavior

Rules Severities are clear for all users.
I would recommend using _Needs review_ instead of _Open_
Would love to learn more about the goals for _Note_ rules

**Comment by AhmedAbdoOrtiga** [comment]
@DaveTryon @RobGallo @ferBonnin  I think Dave or Rob would be the best to help Fer especially with the second part "Would love to learn more about the goals for Note rules"

**Comment by DaveTryon** [comment]
@juchampa is going to confer with @ferBonnin to come up with a proposed description, then we can update as needed.

**Comment by chingucoding** [comment]
If you decided on what the best way to solve this would be, I would gladly help implement an improvement for this :)

**Comment by ferBonnin** [comment]
> If you decided on what the best way to solve this would be, I would gladly help implement an improvement for this :)

thanks @chingucoding! As soon as we sync on this we will reply here and let you know :smile:

**Comment by asksep** [comment]
PMs met with Rob and decided to change Note/Open and to "Needs Review" to add more clarity of expectation to users.

**Comment by DaveTryon** [comment]
Marking this as resolved. Will mark as closed once we release the next version of Axe.Windows

**Comment by DaveTryon** [comment]
@ferBonnin, we've updated https://github.com/microsoft/axe-windows/blob/main/docs/RulesDescription.md, which may be enough to close it. The changes will also be in our next release after we complete the backend work for known framework bugs. Please feel free to close out as appropriate
