### ISSUE TITLE
[BUG] False positive for "The name property of an element should not contain class names like 'Microsoft.*.*' or 'Windows.*.*'"

### ISSUE THREAD

**Issue by jalkire** [microsoft/axe-windows#629]
## Describe the bug
There are cases where the name property for an element begins with "Microsoft." or "Windows." but is not a class name automatically used as the element's name. For example, a hyperlink could be labelled "Microsoft.com" because it links to microsoft.com. In this case, the name is correct.

## Current state
We are keeping this bug open so users can report any other instances when they find a false-positive in this rule so we can understand better how to address it.
We welcome feedback for improving the heuristic that detects class name strings in the Name property.

## Additional context
We will continue to refine our approach so that this rule does not produce false positives.

In the meantime, if you should encounter this error, please let us know in this bug.

**Comment by jalkire** [comment]
Noting that a user reported this false positive caused by a list item displaying packages which happened to start with "Microsoft."

**Comment by jalkire** [comment]
Noting that #485 discusses this rule

**Comment by DaveTryon** [comment]
The noise from this was significantly reduced by #880. Closing now since we don't think there's a lot more to do here.
