### ISSUE TITLE
[BUG] Improve Message: "A split button must not support both the Invoke and Toggle patterns"

### ISSUE THREAD

**Issue by lihas** [microsoft/axe-windows#653]
Please check whether the bug has [already been filed](https://github.com/Microsoft/axe-windows/issues).

## Describe the bug
For a win32 split button (child of win32 toolbar), if it supports IExpandCollapseProvider, but neither IToggleProvider, nor IInvokeProvider, `SplitButtonInvokeAndTogglePatterns ` rule shows the following error.
`A split button must not support both the Invoke and Toggle patterns`.

The bug is in `SplitButtonInvokeAndTogglePatterns::PassesTest`. 
The following condition has to be satisfied for the test to pass.
`var condition = (Patterns.Invoke | Patterns.Toggle)
                & ~(Patterns.Invoke & Patterns.Toggle);`

Now if a split button does not support both Invoke, and Toggle patterns, the part before & operator results in false, making the whole test return false.

Either this or the error message is wrong. If it is not okay for such controls to support neither of the two patterns, the message should state it. Reading the message lead me believe that my control is supporting both Toggle, and Invoke patterns.

**To Reproduce**
1. Create a sample win32 toolbar which has a split button control.
2. The provider for the split button control should support ExpandCollapse pattern, but neither of Toggle, and Invoke patterns.
3. Run accessibility insights on it, and see the error.

![Accessibility insights error](https://user-images.githubusercontent.com/1687568/141705220-02a13d95-5dd6-454d-84be-373fe25c5df4.png)

## Expected behavior

When both Toggle, and Invoke patterns are not handled, the test for `SplitButtonInvokeAndTogglePatterns` should pass.

## Actual behavior

When both Toggle, and Invoke patterns are not handled, the test for `SplitButtonInvokeAndTogglePatterns` fails, as of now.

## Screenshots or .GIF

The following image shows that while the control supports, ExpandCollapse pattern, it does not support Toggle, and Invoke patterns.
The condition however is set in such a way that it causes the test to fail.

![image](https://user-images.githubusercontent.com/1687568/141705021-56f97575-10a0-4234-a22a-78c9d3b6cf69.png)

## Desktop (please complete the following information):

 - OS: Windows 10 20H2 19042.1348
 - Accessibility Insights for Windows Version: 1.1.1741.1
 - Target Application: 
 - Target Application Version: 

## Additional context

Priority requested -

**Comment by DaveTryon** [comment]
Thanks, @lihas! We'll take a look. Just to make sure that we're looking at the same thing you are, can you please attach one or both of the following:
1. A simple app that we can build on our end that shows the problem.
2. An a11ytest file showing the error.

Thanks again!

**Comment by DaveTryon** [comment]
Hello again, @lihas! I've looked at the UIA documentation and the history of this rule, and I can't find any scenario where the docs would justify having neither `TogglePattern` nor `InvokePattern`. I tried adding a simple `SplitButton` into a Win32 app, and wasn't able to reproduce the failure that you're describing. I'm afraid that we'll need to ask you for a small sample project that demonstrates the behavior. Knowing the Windows version that you're running on would also be very helpful, since there's also a chance that this represents a Windows bug. Thanks!

**Comment by lihas** [comment]
` I've looked at the UIA documentation and the history of this rule, and I can't find any scenario where the docs would justify having neither TogglePattern nor InvokePattern`

if the split button should support at least one of the two, then the error message should be modified.
`"A split button must not support both the Invoke and Toggle patterns"`
This is the current error message. This implies that a split button should not have both these patterns together (so having neither is also okay).
A better message would be something like this.
`A split button must not support both the Invoke and Toggle patterns, but must support at least one`.

In my first message I have mentioned that either the test is returning false positive, or the message string is wrong (ambiguous). Apologies for not highlighting the latter as much. I believed that the former is the real issue.

Meanwhile I am working on a sample MFC (win32) app. My split button doesn't support either of the two patterns as of now - invoke, and toggle. It only supports Expand Collapse pattern.

**Comment by lihas** [comment]
sample app - https://github.com/windows-development/SplitButtonAccessibility
The sample app is a native MFC/win32 app.
In the following image "Split btn" is a split button which implements IExpandCollapseProvider, but neither of IToggleProvider, and IInvokeProvider.

![image](https://user-images.githubusercontent.com/1687568/142631312-c9f1ee69-4441-4ee5-a525-0a086c798500.png)

A native win32 split button by default supports IInvokeProvider, and IExpandCollapseProvider, however when a split button is child of a toolbar control, then these interfaces are not implemented by default.

Accessibility insights initially highlights that IExpandCollapseProvider is missing, on implementing this, it starts giving the following error.

`A split button must not support both the Invoke and Toggle patterns.`

![image](https://user-images.githubusercontent.com/1687568/142632146-45f0ca38-52b1-44f2-8b44-73c6215c29f4.png)

This seems to imply that a split button should not implement both these interfaces at once, but it is perfectly fine if neither are implemented.

This leads to two cases.

1.  The error is a false positive, and therefore it is perfectly fine to implement just IExpandCollapseProvider, and neither of IInvokeProvider, and IToggleProvider.
2. A split button must always implement at least one of IToggleProvider, and IInvokeProvider. If this is the case then the error message should be modified to call this out, eg. - "A split button must not support both the Invoke and Toggle patterns, but must support at least one of them"

**Comment by DaveTryon** [comment]
Thanks, @lihas! I'll take a look at this on Monday. One more question--what OS were you running when you ran the scan? We've had reports of odd problems with pattern detection on Windows 11, so it would definitely be interesting to know if you encountered this on Windows 11.

**Comment by DaveTryon** [comment]
Thanks, @lihas! I have a repro of this using your sample code and Win10. We'll need to investigate it from our side. Marking as ready for triage.

**Comment by lihas** [comment]
Dave, the bug is neither in MFC, nor in the detection of patterns.
I debugged axe, and accessibility insights (after locally building them both).
The patterns supported by my split button are getting detected correctly.
Also, although an MFC app, MFC has no role to play here since I am implementing the provider from scratch.
I can create a sample in pure win32 (without use of MFC) if required.
After reading the link shared by you, I think the best way forward would be to modify the error message displayed.

**Comment by lihas** [comment]
@DaveTryon Please let me know if you need more information.

**Comment by DaveTryon** [comment]
We triaged this today. The consensus is to change the primary message to "A split button must support exactly one of the Invoke or Toggle patterns"

We will create separate issues that deal with false positives triggered by generic SplitButton items supported in Win32, UWP, and (potentially) MFC.

**Comment by DaveTryon** [comment]
I'll also move this to the Axe.Windows repo.

**Comment by chingucoding** [comment]
@DaveTryon Mind if I work on this issue?

**Comment by DaveTryon** [comment]
@chingucoding, please feel free to take a stab at rewording the text. You'll also need to take a look at the HowToFix description. These are intentionally short because there's a cap on the maximum length of a bug sent to ADO. Please try to keep this in mind when wordsmithing.

**Comment by DaveTryon** [comment]
The bug text has been fixed in [Axe.Windows 1.1.2](https://github.com/microsoft/axe-windows/releases/tag/v1.1.2). I'll update this bug once the Canary version of AIWin picks up the fix

**Comment by DaveTryon** [comment]
Hello, @lihas! This change is now live in our release at https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1836.01. You can easily use this build just by switching to the Canary release channel. Please take a look, then close the bug after you've regressed it. Thanks!

**Comment by lihas** [comment]
Installed Canary Release: v1.1.1836.01 from the link given above.
I am able to see the updated message.
Bug is fixed.
Closing this issue.
