### ISSUE TITLE
[False Positive] Win32 SplitButton creates error on inner element

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/axe-windows#659]
## Describe the bug

The Win32 SplitButton control is implemented via nested SplitButton elements. The parent element supports the ExpandCollapse pattern, but the child element does not. We should modify the `ControlShouldSupportExpandCollapsePattern` to exclude the child SplitButton element on Win32.

**To Reproduce**

1. Start the [Win32ControlSampler](https://github.com/microsoft/axe-windows/blob/main/tools/Win32ControlSampler/Win32ControlSampler.exe) app
2. Scan it with the Axe.Windows CLI
3. Load the a11ytest file into Accessibility Insights for Windows
4. Expand to the SplitButton child, and see the following error: **An element of the following ControlType must support the ExpandCollapse pattern**

## Expected behavior
The ExpandCollapse pattern is supported on the parent; its absence on the child should not produce an error

## Actual behavior
The code incorrectly complains that the child has no ExpandCollapse pattern

## Desktop (please complete the following information):

 - OS: Windows 10 21H1
 - Accessibility Insights for Windows Version: 1.1.1789.1
 - Target Application: Win32ControlSampler.exe

## Additional context

This was created in response to investigation of #653

**Comment by DaveTryon** [comment]
We discussed this in triage on 11/29

**Comment by chingucoding** [comment]
What would be the best way to fix this? Check if we have two SplitButtons nested inside each other and skip the second one?

**Comment by DaveTryon** [comment]
@chingucoding, it would be along the same lines as #575 or #651. In `ControlShouldSupportExpandCollapsePattern.Condition`, I'd probably create a local variable that specifically excludes a child SplitButton:
```
var eligibleSplitButton = SplitButton & ~Parent(SplitButton);
```
...then replace `SplitButton` with `eligibleSplitButton` in line 34.

This adds some complexity to the unit test since what used to be 2 test cases now becomes several.

**Comment by DaveTryon** [comment]
Marking this as resolved until we release a new version of Axe.Windows

**Comment by DaveTryon** [comment]
This has been fixed in [Axe.Windows 1.1.2](https://github.com/microsoft/axe-windows/releases/tag/v1.1.2)
