### ISSUE TITLE
[BUG] Deadlock in TreeWalkerForLive.GetTreeHierarchy

### ISSUE THREAD

**Issue by Alexey42** [microsoft/axe-windows#722]
Deadlock in LINQ AsParallel.ForAll loop when calling TreeWalkerForLive.GetTreeHierarchy with desktop element for the second time. If i use foreach instead of ForAll everything is ok. 

You can reproduce it by calling TreeWalkerForLive.GetTreeHierarchy(A11yAutomation.ElementFromDesktop(), TreeViewMode.Control) twice. 

I expected i can update children this way but it just locks my app. The fact that usual foreach works fine is confusing me.

**Comment by sfoslund** [comment]
Hi @Alexey42, thanks for using axe windows! Can you please provide a little more information on how to reproduce this issue? I've attached a simple console app I used to try to repro but I wasn't able to reproduce the deadlock. If you could provide more repro instructions or a repro application that would be very helpful, thanks!

[DeadlockRepro.zip](https://github.com/microsoft/axe-windows/files/9021273/DeadlockRepro.zip)

**Comment by Alexey42** [comment]
Hi. It should be WPF application and second call is in ui event. Example code (https://github.com/Alexey42/testApp):

public partial class MainWindow : Window
    {
        A11yElement element;
        TreeWalkerForLive tw;

        public MainWindow()
        {
            InitializeComponent();

            element = A11yAutomation.ElementFromDesktop();
            tw = new TreeWalkerForLive();
            tw.GetTreeHierarchy(element, Axe.Windows.Core.Enums.TreeViewMode.Control);
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            tw.GetTreeHierarchy(element, Axe.Windows.Core.Enums.TreeViewMode.Control);
        }
    }

**Comment by sfoslund** [comment]
@Alexey42 thanks for the repro project, I was able to reproduce this behavior with the test app you provided.
