### ISSUE TITLE
[Feature Request] Need Task<ScanResults> IScanner.ScanAsync()

### ISSUE THREAD

**Issue by chabiss** [microsoft/axe-windows#732]
## Is your feature request related to a problem? Please describe.
Currently the call to ScanResults IScanner.Scan() will result in a blocking call that will blocked the host making the call and bloking the UI thread, which is not desirable. 

## Describe the solution you'd like
We need Task<ScanResults> IScanner.ScanAsync() which allows the scanner to run asynchronously in a background thread

## Describe alternatives you've considered
No other alternative considered. 

## Additional context
N/A

**Comment by DaveTryon** [comment]
In offline conversations, having proper cancellation is part of the ask, even though it's not called out in the description.

**Comment by ferBonnin** [comment]
Thanks for the feature request, @chabiss, marking this as needs investigation to analyze on our side.

**Comment by DaveTryon** [comment]
We're actively working on this feature

**Comment by DaveTryon** [comment]
@chabiss, This is included in version 2.0.0. Release details are at https://github.com/microsoft/axe-windows/releases/tag/v2.0.0. Closing this issue
