### ISSUE TITLE
[Feature Request] NativeMethods.SetProcessDPIAware() should be reset after scan

### ISSUE THREAD

**Issue by chabiss** [microsoft/axe-windows#733]
## Describe the bug
The call to SetProcessDPIAware()
https://github.com/microsoft/axe-windows/blob/4a09d8728ed72fa9d307052a52a1dd4d9cee1258/src/Automation/SnapshotCommand.cs

Will affect any host application integrating axe-window into their product and it's not undone once the scan is completed.  Either remove the call or bring the host application state to where it was before.

**Comment by spadapet** [comment]
I think a good alternative to SetProcessDPIAware() is SetThreadDpiAwarenessContext(), which just changes the current thread and also allows you to switch the thread's awareness back to the way it was:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setthreaddpiawarenesscontext

**Comment by ferBonnin** [comment]
Thanks for the feature request, @chabiss, marking this as needs investigation to analyze on our side.

**Comment by DaveTryon** [comment]
This has been merged into main and will be included in an upcoming release of Axe.Windows. We'll close it out once we release the updated package to GitHub

**Comment by DaveTryon** [comment]
@chabiss, This is included in version 2.0.0. Release details are at https://github.com/microsoft/axe-windows/releases/tag/v2.0.0. Closing this issue
