### ISSUE TITLE
[Feature Request] Make scans against Chromium-based UIs more actionable

### ISSUE THREAD

**Issue by dbjorge** [microsoft/axe-windows#836]
## Is your feature request related to a problem? Please describe.

This issue is based on discussion with @RobGallo and @DaveTryon after several customer interactions where users attempting to scan apps that are Chromium-based get confused.

The most common case is a user trying to scan a browser (Edge, Chrome, etc) with their page loaded, but we've also seen cases where a user has their own Windows app that embeds Chromium (eg, via Electron or WebView2).

There are two related problems that happen when a user does this:

* Most ATs special case Chromium instances such that it's a lot more useful for practical accessibility purposes to scan web content with a web scanner like Accessibility Insights for Web, rather than with axe-windows/Accessibility Insights for Windows. However, axe-windows results don't make any mention of this, even though we could easily distinguish these cases programmatically (by looking for a FrameworkId UIA property of "Chrome").
* Even with an absolutely minimal WebView2 usage serving an empty page with no issues, there are a few low-severity issues that axe-windows flags that are essentially framework issues (~10 `BoundingRectangleNotNull` violations). Users can't do anything about these, but we don't currently treat them as framework issues.

## Describe the solution you'd like

Rob and I think we'd ideally handle this on the axe-windows side similarly to how we treat old edge - create a rule which specifically detects an embedded chromium instance (via FrameworkId "Chome") and present a specific error that directly instructs users to scan the contents of the browser with a web-based scanner. Such a rule should probably somehow suppress any further errors in descendants of the root "Chrome" element - this will require some new form of handling, we don't currently have any other rules that do this type of subtree suppression.

It's a little questionable to call this an "Error" since we don't really want to treat it as an error to use a WebView2 at all, but we don't really have a better means to present actionable feedback to a user about needing an extra step for scanning such a component. I think that a single actionable error would clearly be a lot better than the current case of "dozens or hundreds of inactionable errors", though.

## Describe alternatives you've considered

* The real gold standard in terms of customer ease-of-use might be to actually perform an axe-core scan inside the detected chromium instance somehow. But we think this would probably be technically infeasible to do automatically unless the Chromium instance were accepting CDP debugger commands, and it would be a huge chunk of work to present it reasonably.
* It would be good to investigate/file bugs against the `BoundingRectangleNotNull` violations that are consistently present regardless of page content. We did some initial investigation and think this is probably an issue on the Chromium side rather than the WebView2/MSAA_Proxy side, but didn't nail down an exact location. If we wanted to follow up on this, good contacts to reach out to for more context would be the folks marked as the [Chromium windows accessibility platform OWNERS](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/platform/OWNERS;bpv=1;bpt=0). However, we think pushing on these are pretty low priority; the issues themselves are such low severity that we think it would be hard to get traction on them, so if we end up making the proposed rule above that would mask them anyway, it doesn't feel worth the effort to try to drive them to resolution.

## Additional context

n/a

**Comment by ferBonnin** [comment]
Triaged with the team. 
We will show a Framework rule error and then eliminate or not scan the Chromium component

**Comment by DaveTryon** [comment]
After discussion in Windows triage, this will require some fundamental changes. We feel this needs to be treated as a full feature and not as a kluge fix.

**Comment by Gso-1** [comment]
> ## ¿Su solicitud de función está relacionada con un problema? Sírvase describir.
> Este problema se basa en la discusión con y después de varias interacciones con los clientes en las que los usuarios que intentan escanear aplicaciones basadas en Chromium se confunden.
> 
> El caso más común es un usuario que intenta escanear un navegador (Edge, Chrome, etc.) con su página cargada, pero también hemos visto casos en los que un usuario tiene su propia aplicación de Windows que incrusta Chromium (por ejemplo, a través de Electron o WebView2).
> 
> Hay dos problemas relacionados que ocurren cuando un usuario hace esto:
> 
> * La mayoría de los AT utilizan instancias especiales de Chromium, de modo que es mucho más útil para fines prácticos de accesibilidad escanear contenido web con un escáner web como Accessibility Insights for Web, en lugar de con axe-windows/Accessibility Insights for Windows. Sin embargo, los resultados de axe-windows no hacen ninguna mención de esto, aunque podríamos distinguir fácilmente estos casos mediante programación (buscando una propiedad UIA de FrameworkId de "Chrome").
> * Incluso con un uso absolutamente mínimo de WebView2 que sirve una página vacía sin problemas, hay algunos problemas de baja gravedad que marcan axe-windows que son esencialmente problemas de marco (~ 10 violaciones). Los usuarios no pueden hacer nada al respecto, pero actualmente no los tratamos como problemas de marco.`BoundingRectangleNotNull`
> 
> ## Describa la solución que desea
> Rob y yo creemos que idealmente manejaríamos esto en el lado de las ventanas de hacha de manera similar a cómo tratamos el borde antiguo: crear una regla que detecte específicamente una instancia de cromo incrustada (a través de FrameworkId "Chome") y presentar un error específico que indique directamente a los usuarios que escaneen el contenido del navegador con un escáner basado en la web. Tal regla probablemente debería suprimir de alguna manera cualquier error adicional en los descendientes del elemento raíz "Chrome"; esto requerirá una nueva forma de manejo, actualmente no tenemos ninguna otra regla que haga este tipo de supresión de subárbol.
> 
> Es un poco cuestionable llamar a esto un "Error", ya que realmente no queremos tratarlo como un error para usar un WebView2 en absoluto, pero realmente no tenemos un mejor medio para presentar comentarios procesables a un usuario sobre la necesidad de un paso adicional para escanear dicho componente. Sin embargo, creo que un solo error procesable sería claramente mucho mejor que el caso actual de "docenas o cientos de errores inaccionables".
> 
> ## Describa las alternativas que ha considerado
> * El verdadero estándar de oro en términos de facilidad de uso para el cliente podría ser realizar un escaneo de núcleo de hacha dentro de la instancia de cromo detectada de alguna manera. Pero creemos que esto probablemente sería técnicamente inviable de hacer automáticamente a menos que la instancia de Chromium aceptara comandos del depurador CDP, y sería una gran cantidad  de trabajo presentarlo razonablemente.
> * Sería bueno investigar / archivar errores contra las violaciones que están constantemente presentes independientemente del contenido de la página. Hicimos una investigación inicial y creemos que esto es probablemente un problema en el lado de Chromium en lugar del lado de WebView2 / MSAA_Proxy, pero no definimos una ubicación exacta. Si quisiéramos hacer un seguimiento de esto, los buenos contactos a los que llegar para obtener más contexto serían las personas marcadas como PROPIETARIOS de la [plataforma de accesibilidad de Windows de Chromium](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/platform/OWNERS;bpv=1;bpt=0). Sin embargo, creemos que presionar sobre estos es una prioridad bastante baja; Los problemas en sí son de tan baja gravedad que creemos que sería difícil obtener tracción sobre ellos, por lo que si terminamos haciendo la regla propuesta arriba que los enmascararía de todos modos, no vale la pena el esfuerzo de tratar de llevarlos a la resolución.`BoundingRectangleNotNull`
> 
> ## Contexto adicional
> n/d

Yo le cobraría 

> ## ¿Su solicitud de función está relacionada con un problema? Sírvase describir.
> Este problema se basa en la discusión con y después de varias interacciones con los clientes en las que los usuarios que intentan escanear aplicaciones basadas en Chromium se confunden.
> 
> El caso más común es un usuario que intenta escanear un navegador (Edge, Chrome, etc.) con su página cargada, pero también hemos visto casos en los que un usuario tiene su propia aplicación de Windows que incrusta Chromium (por ejemplo, a través de Electron o WebView2).
> 
> Hay dos problemas relacionados que ocurren cuando un usuario hace esto:
> 
> * La mayoría de los AT utilizan instancias especiales de Chromium, de modo que es mucho más útil para fines prácticos de accesibilidad escanear contenido web con un escáner web como Accessibility Insights for Web, en lugar de con axe-windows/Accessibility Insights for Windows. Sin embargo, los resultados de axe-windows no hacen ninguna mención de esto, aunque podríamos distinguir fácilmente estos casos mediante programación (buscando una propiedad UIA de FrameworkId de "Chrome").
> * Incluso con un uso absolutamente mínimo de WebView2 que sirve una página vacía sin problemas, hay algunos problemas de baja gravedad que marcan axe-windows que son esencialmente problemas de marco (~ 10 violaciones). Los usuarios no pueden hacer nada al respecto, pero actualmente no los tratamos como problemas de marco.`BoundingRectangleNotNull`
> 
> ## Describa la solución que desea
> Rob y yo creemos que idealmente manejaríamos esto en el lado de las ventanas de hacha de manera similar a cómo tratamos el borde antiguo: crear una regla que detecte específicamente una instancia de cromo incrustada (a través de FrameworkId "Chome") y presentar un error específico que indique directamente a los usuarios que escaneen el contenido del navegador con un escáner basado en la web. Tal regla probablemente debería suprimir de alguna manera cualquier error adicional en los descendientes del elemento raíz "Chrome"; esto requerirá una nueva forma de manejo, actualmente no tenemos ninguna otra regla que haga este tipo de supresión de subárbol.
> 
> Es un poco cuestionable llamar a esto un "Error", ya que realmente no queremos tratarlo como un error para usar un WebView2 en absoluto, pero realmente no tenemos un mejor medio para presentar comentarios procesables a un usuario sobre la necesidad de un paso adicional para escanear dicho componente. Sin embargo, creo que un solo error procesable sería claramente mucho mejor que el caso actual de "docenas o cientos de errores inaccionables".
> 
> ## Describa las alternativas que ha considerado
> * El verdadero estándar de oro en términos de facilidad de uso para el cliente podría ser realizar un escaneo de núcleo de hacha dentro de la instancia de cromo detectada de alguna manera. Pero creemos que esto probablemente sería técnicamente inviable de hacer automáticamente a menos que la instancia de Chromium aceptara comandos del depurador CDP, y sería una gran cantidad de trabajo presentarlo razonablemente.
> * Sería bueno investigar / archivar errores contra las violaciones que están constantemente presentes independientemente del contenido de la página. Hicimos una investigación inicial y creemos que esto es probablemente un problema en el lado de Chromium en lugar del lado de WebView2 / MSAA_Proxy, pero no definimos una ubicación exacta. Si quisiéramos hacer un seguimiento de esto, los buenos contactos a los que llegar para obtener más contexto serían las personas marcadas como PROPIETARIOS de la [plataforma de accesibilidad de Windows de Chromium](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/platform/OWNERS;bpv=1;bpt=0). Sin embargo, creemos que presionar sobre estos es una prioridad bastante baja; Los problemas en sí son de tan baja gravedad que creemos que sería difícil obtener tracción sobre ellos, por lo que si terminamos haciendo la regla propuesta arriba que los enmascararía de todos modos, no vale la pena el esfuerzo de tratar de llevarlos a la resolución.`BoundingRectangleNotNull`
> 
> ## Contexto adicional
> n/d

Yo le cobraría 45000CLP por la suscripción y la pronta asesoría

**Comment by Gso-1** [comment]
> ## ¿Su solicitud de función está relacionada con un problema? Sírvase describir.
> Este problema se basa en la discusión con y después de varias interacciones con los clientes en las que los usuarios que intentan escanear aplicaciones basadas en Chromium se confunden.
> 
> El caso más común es un usuario que intenta escanear un navegador (Edge, Chrome, etc.) con su página cargada, pero también hemos visto casos en los que un usuario tiene su propia aplicación de Windows que incrusta Chromium (por ejemplo, a través de Electron o WebView2).
> 
> Hay dos problemas relacionados que ocurren cuando un usuario hace esto:
> 
> * La mayoría de los AT utilizan instancias especiales de Chromium, de modo que es mucho más útil para fines prácticos de accesibilidad escanear contenido web con un escáner web como Accessibility Insights for Web, en lugar de con axe-windows/Accessibility Insights for Windows. Sin embargo, los resultados de axe-windows no hacen ninguna mención de esto, aunque podríamos distinguir fácilmente estos casos mediante programación (buscando una propiedad UIA de FrameworkId de "Chrome").
> * Incluso con un uso absolutamente mínimo de WebView2 que sirve una página vacía sin problemas, hay algunos problemas de baja gravedad que marcan axe-windows que son esencialmente problemas de marco (~ 10 violaciones). Los usuarios no pueden hacer nada al respecto, pero actualmente no los tratamos como problemas de marco.`BoundingRectangleNotNull`
> 
> ## Describa la solución que desea
> Rob y yo creemos que idealmente manejaríamos esto en el lado de las ventanas de hacha de manera similar a cómo tratamos el borde antiguo: crear una regla que detecte específicamente una instancia de cromo incrustada (a través de FrameworkId "Chome") y presentar un error específico que indique directamente a los usuarios que escaneen el contenido del navegador con un escáner basado en la web. Tal regla probablemente debería suprimir de alguna manera cualquier error adicional en los descendientes del elemento raíz "Chrome"; esto requerirá una nueva forma de manejo, actualmente no tenemos ninguna otra regla que haga este tipo de supresión de subárbol.
> 
> Es un poco cuestionable llamar a esto un "Error", ya que realmente no queremos tratarlo como un error para usar un WebView2 en absoluto, pero realmente no tenemos un mejor medio para presentar comentarios procesables a un usuario sobre la necesidad de un paso adicional para escanear dicho componente. Sin embargo, creo que un solo error procesable sería claramente mucho mejor que el caso actual de "docenas o cientos de errores inaccionables".
> 
> ## Describa las alternativas que ha considerado
> * El verdadero estándar de oro en términos de facilidad de uso para el cliente podría ser realizar un escaneo de núcleo de hacha dentro de la instancia de cromo detectada de alguna manera. Pero creemos que esto probablemente sería técnicamente inviable de hacer automáticamente a menos que la instancia de Chromium aceptara comandos del depurador CDP, y sería una gran cantidad de trabajo presentarlo razonablemente.
> * Sería bueno investigar / archivar errores contra las violaciones que están constantemente presentes independientemente del contenido de la página. Hicimos una investigación inicial y creemos que esto es probablemente un problema en el lado de Chromium en lugar del lado de WebView2 / MSAA_Proxy, pero no definimos una ubicación exacta. Si quisiéramos hacer un seguimiento de esto, los buenos contactos a los que llegar para obtener más contexto serían las personas marcadas como PROPIETARIOS de la [plataforma de accesibilidad de Windows de Chromium](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/platform/OWNERS;bpv=1;bpt=0). Sin embargo, creemos que presionar sobre estos es una prioridad bastante baja; Los problemas en sí son de tan baja gravedad que creemos que sería difícil obtener tracción sobre ellos, por lo que si terminamos haciendo la regla propuesta arriba que los enmascararía de todos modos, no vale la pena el esfuerzo de tratar de llevarlos a la resolución.`

**Comment by DaveTryon** [comment]
The Chromium rule now triggers exactly once for each Chromium Document. All rules are suppressed for elements within the Chromium Document

**Comment by codeofdusk** [comment]
Released as part of [2.2.0](https://github.com/microsoft/axe-windows/releases/tag/v2.2.0). Closing as complete.
