### ISSUE TITLE
BoundingRectangle failures reported for hidden tab control in old style wizards

### ISSUE THREAD

**Issue by chrisoldwood** [microsoft/axe-windows#92]
In older style native Win32 application wizards there is a hidden tab control near the top. This hidden tab control, which is purely an implementation detail, is being picked up by the Insights tool and failures reported against the tab positions and labels.

Here is an example of the failures reported by Insights:

![Insights-Errors](https://user-images.githubusercontent.com/2768826/60688526-a669e780-9ead-11e9-80da-a4118e7bc0c7.gif)

And here is the overlay window showing where the failures are detected:

![Insights-Dialog](https://user-images.githubusercontent.com/2768826/60688546-c699a680-9ead-11e9-8acd-bca341d3f2fc.gif)

These screenshots are not taken from the real application which I am working on because that is private, and so I've found a publicly available example instead. The application above is a free application called [Source Monitor](http://www.campwoodsw.com/sourcemonitor.html) which I know uses older style wizards and is still actively maintained. The wizard displayed above is the "New Project" wizard which contains 7 pages.

Please can you explain why the tool is reporting failures with this hidden control, as it is not obvious how it affects accessibility as the user will never interact with it.

**Comment by karanbirsingh** [comment]
@chrisoldwood The rule engine used by insights lives in this GitHub repo so I've transferred the issue. We will take a look at this soon - thanks!

**Comment by karanbirsingh** [comment]
Hi @chrisoldwood, I chatted with @RobGallo about this. Thanks for the report & let us know what you think.

I have attached an a11ytest file below of SourceMonitor. To open it in Accessibility Insights, please rename it to SourceMonitor.a11ytest (GitHub doesn't allow custom extension uploads).
[SourceMonitor.zip](https://github.com/microsoft/axe-windows/files/3369796/SourceMonitor.zip)

**bounding rectangles:** 
The BoundingRectangle failures were changed to warnings in `Axe.Windows 0.2`. Accessibility Insights uses `0.2` in [canary](https://github.com/microsoft/accessibility-insights-windows/releases), but not in production yet. 

**names:** 
It would be interesting to filter these cases out - the challenge is distinguishing this wizard case from other Win32 applications with empty-name tab items. Like you mention, it's unlikely a keyboard user will encounter the tab items in this dialog (they're not in the tab order). Axe.Windows only has access to the UI Automation tree, in which the tab items report themselves as keyboard-focusable. Unless we can exclude this wizard case via UI Automation properties, it's difficult to change the rule without introducing false negatives in other Win32 applications.

**Comment by chrisoldwood** [comment]
Thanks for acknowledging the issue. I agree that it is going to be tricky to distinguish old style wizards because the point is to abstract the UI from the client 😃. If you want to close this issue then go ahead, my main aim was to document the problem for myself and others. In the meantime I will look into finding a way to make this detectable in a safe way.

**Comment by karanbirsingh** [comment]
Thanks @chrisoldwood - we'll close this. Do let us know if something comes to mind!
