### ISSUE TITLE
Update WiX from v3 to v4

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/axe-windows#946]
This is the analog of https://github.com/microsoft/accessibility-insights-windows/issues/1641, where @BMurri requested an issue to convert the WiX support form 3 to 4. The MSI file is generated in the `src/CLI_Installer` folder.

**Comment by DaveTryon** [comment]
@BMurri, please self-assign (GitHub isn't allowing me to assign this to you)

**Comment by BMurri** [comment]
> @BMurri, please self-assign (GitHub isn't allowing me to assign this to you)

It's not allowing me either, but we'll use this to say this issue is assigned to me.

**Comment by DaveTryon** [comment]
It allowed me to assign it once you commented on it
