### ISSUE TITLE
[BUG] MSI installer should warn user about unsupported OS

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/axe-windows#980]
## Describe the bug

In #833, we changed the CLI from .NET Core 3.1 to .NET 6.0. As a result of this change, the CLI no longer supports Windows 7. The installer should check for an OS version earlier than Windows 10, then display an error message that explains that the CLI is only supported on Windows 10 or newer.

**To Reproduce**

1. Go to https://github.com/microsoft/axe-windows/releases/tag/v2.3.0
2. Download the MSI installer
3. Install it on Windows 7 (you'll need to install .NET 6.0 before running the installer)
4. Installation will succeed
5. Launch `AxeWindowsCLI.exe`

## Expected behavior

The app should display the supported help screen

## Actual behavior

The app displays a message that the app isn't compatible with the OS

## Desktop (please complete the following information):

 - OS: Windows 7
 - Axe Windows Version: 2.3.0

## Additional context

Priority requested -

**Comment by v-singhanjal** [comment]
We have done changes to get the message regarding the Windows Version on Windows7. The message looks like this:
![Screenshot 2023-12-18 185645](https://github.com/microsoft/axe-windows/assets/150343275/51a4dca9-d2af-4fdc-93f0-99d40328c1f8)
Please review and let us know if any further changes needs to be done.

**Comment by DaveTryon** [comment]
Released in https://github.com/microsoft/axe-windows/releases/tag/v2.3.1
