### ISSUE TITLE
[General Question] How to disable rules

### ISSUE THREAD

**Issue by ChristoWolf** [microsoft/axe-windows#984]
## Is there any API to disable rules on a config or scan level? 

Hi! 

I looked a bit through the code, but couldn't find out how to disable rules. 
Would appreciate any help :)

**Comment by v-prachin** [comment]
Acknowledged the issue and looking into it.

**Comment by v-prachin** [comment]
The option to disable rules is currently unavailable. We kindly request you to create a separate issue for any rule that is encountering errors or not functioning correctly. This will enable us to conduct an assessment of the issue and implement the necessary corrective measures for the specific rule under consideration.

**Comment by ChristoWolf** [comment]
Hi @v-prachin!

Thanks for looking into it, looks like I did not miss this while looking through the code.
The rules are fine as far as I can see, it's just that I would like to disable some whenever needed.

For now, I will just filter the `ScanResult`s on my own, which is sufficient.
