### ISSUE TITLE
[General Question] False positive for "The Name property must not include the element's control type."

### ISSUE THREAD

**Issue by MarcoMusculiato** [microsoft/axe-windows#987]
**Issue**
As our developers are working and validating the 508 properties for the controls, there is a situation where the rule detects control type strings within Name property incorrectly return an error.
In our specific case, this screen contains a group where its filters apply the Group By used by the report.
In this situation, we do not have any other option but name the group control, Group By.

![image](https://github.com/microsoft/axe-windows/assets/155778864/fff8de92-c6c7-46d9-8261-0a059efca07a)

Is there any work-around on this situation to fix this issue?
This might be related to https://github.com/microsoft/axe-windows/issues/330

Thanks,
Marco.

**Comment by v-viyada** [comment]
This is know false positive. There is no available work around and you can ignore the error.
