### ISSUE TITLE
[General Question] Why does axe-windows not include axe-core and its rules?

### ISSUE THREAD

**Issue by ChristoWolf** [microsoft/axe-windows#989]
Hi!

I think the question speaks for itself.

For example, axe-windows scans do not include basic WCAG rules like color contrast evaluation.
This also implies that FastPass tests using Accessibility Insights for Windows do not scan/report such issues.

What is the reasoning there?

**Comment by codeofdusk** [comment]
axe-core is a web-based scanning engine that runs in the context of a web browser. Since Axe-windows runs at the UI Automation level, it isn't able to interrogate the document object model (DOM) in the same ways. Accessibility Insights for Windows does include colour contrast evaluation tools, but these aren't exposed in Axe-windows' public interfaces at this time.

**Comment by ChristoWolf** [comment]
Thanks for the quick response @codeofdusk!

Yeah I figured, I've seen then that axe-core actually inspects the DOM.

> but these aren't exposed in Axe-windows' public interfaces at this time

I thought that this could be done using the [ColorContrastAnalyzer](https://github.com/microsoft/axe-windows/tree/main/src/Desktop/ColorContrastAnalyzer)?

**Comment by DaveTryon** [comment]
@ChristoWolf, the DOM supports direct query of the colors in an element; UIA does not. The ColorContrastAnalyzer attempts to _infer_ the colors by scanning a bitmap that corresponds to the on-screen element. It uses heuristics to identify the colors, and it's only sometimes accurate. We've evaluated different ways to improve its accuracy, but without much success. Users can trigger automatic color from Accessibility Insights for Windows ([docs](https://accessibilityinsights.io/docs/windows/getstarted/colorcontrast/#auto-detect-contrast-ratio)), but not from Axe.Windows scans. Our team has no current plans to add this integration.

Thanks for using Axe.Windows! Please feel free to open a new issue if you have additional questions 😄

**Comment by ChristoWolf** [comment]
Thanks for the insights @DaveTryon!
In that case I will simply wrap `ColorContrastAnalyzer` in my APIs.
Are you open for any other tools similar to this analyzer that could be contributed?
